crab status -d results_data/crab_SingleMuon_Run2017B
crab status -d results_data/crab_SingleMuon_Run2017C
crab status -d results_data/crab_SingleMuon_Run2017D
crab status -d results_data/crab_SingleMuon_Run2017E
crab status -d results_data/crab_SingleMuon_Run2017F
crab status -d results_data/crab_SingleElectron_Run2017B
crab status -d results_data/crab_SingleElectron_Run2017C
crab status -d results_data/crab_SingleElectron_Run2017D
crab status -d results_data/crab_SingleElectron_Run2017E
crab status -d results_data/crab_SingleElectron_Run2017F
crab status -d results_data/crab_DoubleMuon_Run2017B
crab status -d results_data/crab_DoubleMuon_Run2017C
crab status -d results_data/crab_DoubleMuon_Run2017D
crab status -d results_data/crab_DoubleMuon_Run2017E
crab status -d results_data/crab_DoubleMuon_Run2017F
crab status -d results_data/crab_DoubleEG_Run2017B
crab status -d results_data/crab_DoubleEG_Run2017C
crab status -d results_data/crab_DoubleEG_Run2017D
crab status -d results_data/crab_DoubleEG_Run2017E
crab status -d results_data/crab_DoubleEG_Run2017F
crab status -d results_data/crab_MuonEG_Run2017B
crab status -d results_data/crab_MuonEG_Run2017C
crab status -d results_data/crab_MuonEG_Run2017D
crab status -d results_data/crab_MuonEG_Run2017E
crab status -d results_data/crab_MuonEG_Run2017F
