crab resubmit -d results_data/crab_SingleMuon_Run2017B
crab resubmit -d results_data/crab_SingleMuon_Run2017C
crab resubmit -d results_data/crab_SingleMuon_Run2017D
crab resubmit -d results_data/crab_SingleMuon_Run2017E
crab resubmit -d results_data/crab_SingleMuon_Run2017F
crab resubmit -d results_data/crab_SingleElectron_Run2017B
crab resubmit -d results_data/crab_SingleElectron_Run2017C
crab resubmit -d results_data/crab_SingleElectron_Run2017D
crab resubmit -d results_data/crab_SingleElectron_Run2017E
crab resubmit -d results_data/crab_SingleElectron_Run2017F
crab resubmit -d results_data/crab_DoubleMuon_Run2017B
crab resubmit -d results_data/crab_DoubleMuon_Run2017C
crab resubmit -d results_data/crab_DoubleMuon_Run2017D
crab resubmit -d results_data/crab_DoubleMuon_Run2017E
crab resubmit -d results_data/crab_DoubleMuon_Run2017F
crab resubmit -d results_data/crab_DoubleEG_Run2017B
crab resubmit -d results_data/crab_DoubleEG_Run2017C
crab resubmit -d results_data/crab_DoubleEG_Run2017D
crab resubmit -d results_data/crab_DoubleEG_Run2017E
crab resubmit -d results_data/crab_DoubleEG_Run2017F
crab resubmit -d results_data/crab_MuonEG_Run2017B
crab resubmit -d results_data/crab_MuonEG_Run2017C
crab resubmit -d results_data/crab_MuonEG_Run2017D
crab resubmit -d results_data/crab_MuonEG_Run2017E
crab resubmit -d results_data/crab_MuonEG_Run2017F
